#!/usr/bin/env bash
set -e

git push origin master
git checkout -B gh-pages
npm run build
git add --force ./pages/* ./style.css
git commit -m 'updated build'
git push origin --force gh-pages
git checkout master
